export const PREMIUM_TOOLS = [
  // Professional Growth
  "LinkedIn Premium",
  "Grammarly Premium",
  "ChatGPT Plus",
  // Design
  "Canva Pro",
  "Adobe Creative Cloud",
  "Final Cut Pro",
  "Figma Pro",
  // Marketing & SEO
  "SEMrush",
  "Ahrefs",
  "BuzzSumo",
  "Moz Pro",
  "Surfer SEO",
  // Productivity
  "Google Workspace",
  "Trello Premium",
  "Notion Premium",
  "Asana Premium",
  "Monday.com",
  "ClickUp",
  // E-Commerce
  "Shopify Plus",
  "Wix Premium",
  "BigCommerce",
  "WooCommerce Premium",
  // Streaming
  "Spotify Premium",
  "YouTube Premium",
  "Netflix Premium",
  "Disney+ Premium",
  // Other popular tools
  "Slack Premium",
  "Zoom Pro",
  "Microsoft 365",
  "Dropbox Business",
  "DocuSign",
  "Mailchimp Premium",
  "HubSpot Premium",
  "Salesforce",
  "Zendesk Suite",
  "Hootsuite Professional",
  "Buffer Premium",
  "LastPass Premium",
  "1Password Teams",
  "Dashlane Business",
  "Quickbooks Premium",
  "Xero Premium",
  "FreshBooks Plus",
  "Calendly Pro",
  "WebFlow Premium",
  "Elementor Pro",
  "Divi Premium",
  "OptinMonster",
  "ConvertKit",
  "ActiveCampaign",
  "Other (Please Specify)",
];